### ISSUE TITLE
Collect information about Calabash sessions

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash-ios#908]
### Motivation

We need to understand how popular Calabash is.

I think a hit counter that tracks some idea of Calabash sessions would be sufficient and unobtrusive.

### Sessions

Session has an environment or context.  A session is an invocation of console or cucumber.

* console session
* cucumber session
* CI (travis, jenkins, circle ci, teamcity)

### TODO

- [x] os => host_os # usage_tracker.rb
- [x] remove include_ip? => # usage_tracker.rb
- [x] Should there be a separate ios and android preferences file? No.
- [ ] Need an interface to disable tracking; first pass should be a console interface.

**Comment by jmoody** [comment]
Our plan is to roll this out for 0.17.0 iOS.

* The first pass will collect only that a console or cucumber has started.
* We will also attempt to determine if the session is running in CI.
* We will not collect the user's IP address
* There will be a way to opt out of sending this information.

For later versions we plan to ask users to _opt into_ allowing us to collect more information.

**Comment by jmoody** [comment]
@sapieneptus @krukow @GlennWilson @jraczak

We'll be doing the same in Calabash Android.

**Comment by jmoody** [comment]
@sapieneptus @TobiasRoikjer 

> Should there be a separate ios and android preferences file? 

I talked briefly with Tobias yesterday about this.  We think no.  If we encounter a user who needs this behavior, we can create a feature request.

**Comment by jmoody** [comment]
Won't be completed before meeting today.

**Comment by sapieneptus** [comment]
@jmoody I don't recall if you ever addressed my comment about collecting more than just `session` ? Eg., `console-session`, `cucumber`, `calabash-ios setup`, etc...

**Comment by jmoody** [comment]
I did leave a comment yesterday about this.  The gist was:  

* small steps, 
* we don't know what we want to collect, 
* the original feature was to get a head count, 
* we are tracking IRB and cucumber usage,
* I agree that there are many other events we might want to track.
